root: ./

​structure:  
    summary: SUMMARY.md​

redirects:  
    4407601802391: apis.md
    4407595916823: allocation.md
    7923409206167: filters-v2.md
    8554606459671: assets-api.md
    8135370079511: asset-diff.md
    7302571484823: audit-api.md
    5843799319703: api-request-recommendation-apply.md
    4407595919895: api-request-right-sizing-v2.md api-request-right-sizing.md
    4407601797911: api-abandoned-workloads.md
    4407595915543: allocation-api.md
    4407595972119: namespace-contacts.md
    4407595922711: architecture.md multi-cluster.md
    4407595974679: open-source-deps.md
    4412369153687: cloud-integration.md resource-consumption.md
    4407595924247: assets.md
    4407595978903: security.md
    4425080011671: ports.md
    4407601807383: cost-allocation.md
    4407595921431: app-memory.md
    4423256582551: resource-consumption.md secondary-clusters.md
    4408095797911: ksm-metrics.md
    4407595937175: business.md
    4407601809175: high-availability.md
    4407601825431: release-process.md
    8428105779095: aws-eks-cost-monitoring.md
    4407595928087: aws-cloud-integrations.md
    4407596808087: aws-marketplace-install.md
    4407596810519: aws-out-of-cluster.md
    4407595952151: long-term-storage-aws.md
    4407596809111: aws-node-price-reconcilitation-methodology.md
    4409859798679: aws-amp-integration.md
    4407595933847: aws-service-account-thanos.md
    4407595934871: azure-config.md
    4407595954327: long-term-storage-azure.md
    4407595936023: azure-out-of-cluster.md
    4407601817495: google-service-account-thanos.md
    4407601822359: long-term-storage-gcp.md
    4407601816087: gcp-out-of-cluster.md
    4442565953943: community-getting-started.md
    8292513994903: opencost-product-comparison.md
    4425134686743: user-metrics.md
    8445296194711: outages.md
    4425132038167: agent.md
    6446286863383: resource-consumption.md secondary-clusters.md
    6152374933655: windows.md
    6737508001687: custom-grafana.md
    4407595950359: index.md
    5703965450647: grafana-cloud-integration.md
    4407601821207: install.md
    4407601818391: helm-install-params.md
    4408175613719: istio-rancher.md
    4413635957271: rafay.md
    4407601795863: air-gapped.md
    7788112146711: install-on-plural.md
    8241029276567: openshift-kubecost-install.md
    4407595968919: multi-cloud.md
    5699259004311: grafana-cloud-integration.md
    4407601810199: env.md
    4407601820055: aws-eks-cost-monitoring.md getting-started.md ingress-examples.md
    4407595970711: multi-cluster.md
    4407595946135: federated-clusters.md
    4407595938327: controller.md
    4407595964695: long-term-storage-aws.md long-term-storage.md secondary-clusters.md
    4407595941015: custom-prom.md getting-started.md
    4407601829655: thanos-upgrade.md
    4407601815191: long-term-storage.md
    4407595985047: user-management.md
    4407601828247: staging.md
    4407595981591: storage.md
    4407595973527: agent.md network-allocation.md
    5699967551639: custom-prom.md
    hc/en-us/articles/4407601826839: spinnaker-custom-webhook.md
    6737520506519: v1-94-turndown-schedule-migration-guide.md
    4407601830679: secondary-clusters.md troubleshoot-install.md
    4407595983127: support-channels.md
    4407595942679: diagnostics.md
    4407601805975: bug-report.md
    4407595947799: getting-started.md
    4407595926423: availability-tiers.md
    5748367035159: cluster-health-score.md
    4407595980311: spot-checklist.md
    4412353032599: spot-cluster-sizing.md
    5843816284823: controller.md guide-one-click-request-sizing.md
    4407601824279: prometheus.md
    4407595975959: partner-metrics.md
    4407601811095: etl-backup.md
    4407595925271: audit.md
    4407595918231: annotations.md
    4407595977879: saved-reports.md
    4407601796759: alerts.md
    4407604999447: markdown.md
    5991192077079: advanced-reports.md
    4407601802391-APIs: apis.md
    4407595916823-Allocation-API: allocation.md
    7923409206167-V2-Filters: filters-v2.md
    8554606459671-Assets-API: assets-api.md
    8135370079511-Asset-Diff-API: asset-diff.md
    7302571484823-Audit-API: audit-api.md
    5843799319703-Container-Request-Recommendation-Apply-APIs: api-request-recommendation-apply.md
    4407595919895-Container-Request-Right-Sizing-API: api-request-right-sizing-v2.md api-request-right-sizing.md
    4407601797911-Abandoned-Workloads: api-abandoned-workloads.md
    4407595915543-Kubecost-APIs: allocation-api.md
    4407595972119-Namespace-Contacts: namespace-contacts.md
    4407595922711-Kubecost-Core-Architecture-Overview: architecture.md multi-cluster.md
    4407595974679-Open-Source: open-source-deps.md
    4412369153687-Cloud-Integrations: cloud-integration.md resource-consumption.md
    4407595924247-Assets: assets.md
    4407595978903-Security: security.md
    4425080011671-Ports: ports.md
    4407601807383-Kubernetes-Cost-Allocation: cost-allocation.md
    4407595921431-Kubecost-Memory-Usage: app-memory.md
    4423256582551-Kubecost-Secondary-Clusters: resource-consumption.md secondary-clusters.md
    4408095797911-Kube-State-Metrics-KSM-Emission: ksm-metrics.md
    4407595937175-Kubecost-Business-Features: business.md
    4407601809175-Kubecost-Enterprise-Features: high-availability.md
    4407601825431-Kubecost-Release-Process: release-process.md
    8428105779095-Amazon-EKS-integration: aws-eks-cost-monitoring.md
    4407595928087-AWS-Cloud-Integration: aws-cloud-integrations.md
    4407596808087-AWS-Marketplace-Install: aws-marketplace-install.md
    4407596810519-AWS-Out-of-Cluster-: aws-out-of-cluster.md
    4407595952151-AWS-Multi-Cluster-Storage-Configuration: long-term-storage-aws.md
    4407596809111-AWS-Node-Price-Reconciliation-Methodology: aws-node-price-reconcilitation-methodology.md
    4409859798679-Amazon-Managed-Service-for-Prometheus: aws-amp-integration.md
    4407595933847-Creating-a-Thanos-IAM-policy: aws-service-account-thanos.md
    4407595934871-Azure-Config: azure-config.md
    4407595954327-Azure-Long-Term-Storage: long-term-storage-azure.md
    4407595936023-Adding-Azure-Out-of-Cluster-Cluster-Costs-into-Kubecost: azure-out-of-cluster.md
    4407601817495-Creating-a-Google-Service-Account: google-service-account-thanos.md
    4407601822359-GCP-Long-Term-Storage: long-term-storage-gcp.md
    4407601816087-GCP-Out-of-Cluster: gcp-out-of-cluster.md
    4442565953943-Getting-Started: community-getting-started.md
    8292513994903-OpenCost-Product-Comparison: opencost-product-comparison.md
    4425134686743-User-Metrics: user-metrics.md
    8445296194711-Outages: outages.md
    4425132038167-Installing-Agent-for-Hosted-Kubecost-Alpha-: agent.md
    6446286863383-Tuning-Resource-Consumption: resource-consumption.md secondary-clusters.md
    6152374933655-Windows-Node-Support: windows.md
    6737508001687-Grafana-Configuration-Guide: custom-grafana.md
    4407595950359-Welcome: index.md
    5703965450647-Grafana-Cloud-Integration-for-Kubecost: grafana-cloud-integration.md
    4407601821207-Installing-Kubecost: install.md
    4407601818391-Helm-Parameters: helm-install-params.md
    4408175613719-Installation-Kubecost-with-Istio-Rancher-: istio-rancher.md
    4413635957271-Installing-Kubecost-with-Rafay: rafay.md
    4407601795863-Installing-in-Air-gapped-Environments: air-gapped.md
    7788112146711-Installing-Kubecost-with-Plural: install-on-plural.md
    8241029276567-Install-Kubecost-on-Redhat-OpenShift-cluster: openshift-kubecost-install.md
    4407595968919-Setting-Up-Cloud-Integrations: multi-cloud.md
    5699259004311-Grafana-Cloud-Integration-for-Kubecost: grafana-cloud-integration.md
    4407601810199-Environment: env.md
    4407601820055-Ingress-Examples: aws-eks-cost-monitoring.md getting-started.md ingress-examples.md
    4407595970711-Multi-cluster: multi-cluster.md
    4407595946135-Federated-Clusters: federated-clusters.md
    4407595938327-Cluster-Controller: controller.md
    4407595964695-Long-Term-Storage: long-term-storage-aws.md long-term-storage.md secondary-clusters.md
    4407595941015-Custom-Prometheus: custom-prom.md getting-started.md
    4407601829655-Thanos-Upgrade: thanos-upgrade.md
    4407601815191-ETL-S3-Backup: long-term-storage.md
    4407595985047-User-Management-SSO-SAML: user-management.md
    4407601828247-Deploy-Kubecost-Staging-Builds: staging.md
    4407595981591-Cost-Analyzer-Persistent-Volume: storage.md
    4407595973527-Network-Traffic-Cost-Allocation: agent.md network-allocation.md
    5699967551639-Grafana-Cloud-Integration-for-Kubecost: custom-prom.md
    hc/en-us/articles/4407601826839-Custom-Webhook-to-Create-a-Kubecost-stage-in-Spinnaker: spinnaker-custom-webhook.md
    6737520506519-v1-94-TurndownSchedule-migration-guide: v1-94-turndown-schedule-migration-guide.md
    4407601830679-Troubleshoot-Install: secondary-clusters.md troubleshoot-install.md
    4407595983127-Getting-Support: support-channels.md
    4407595942679-Kubecost-Diagnostics: diagnostics.md
    4407601805975-Capture-a-bug-report: bug-report.md
    4407595947799-Getting-Started: getting-started.md
    4407595926423-Availability-Tiers: availability-tiers.md
    5748367035159-Cluster-Health-Score-: cluster-health-score.md
    4407595980311-Spot-Checklist: spot-checklist.md
    4412353032599-Spot-Cluster-Sizing: spot-cluster-sizing.md
    5843816284823-Guide-1-click-request-sizing: controller.md guide-one-click-request-sizing.md
    4407601824279-Running-a-query-in-Kubecost-bundled-Prometheus: prometheus.md
    4407595975959-Standardizing-Kubernetes-cost-allocation: partner-metrics.md
    4407601811095-ETL-Backup: etl-backup.md
    4407595925271-Auditing: audit.md
    4407595918231-Enabling-Annotation-Emission: annotations.md
    4407595977879-Saved-Reports: saved-reports.md
    4407601796759-Alerts-Documentation: alerts.md
    4407604999447-Contributing-and-Markdown-Style-Guide: markdown.md
    5991192077079-Advanced-Reporting: advanced-reports.md
