root: ./

​structure:  
    summary: SUMMARY.md​

redirects:  
    hc/en-us/articles/8135370079511-Asset-Diff-API: asset-diff.md
    hc/en-us/articles/8135370079511: asset-diff.md
    8135370079511-Asset-Diff-API: asset-diff.md
    8135370079511: asset-diff.md
